CREATE TABLE Flight(
FLIGHT_ID NUMBER,
FLIGHT_PLANE_ID NUMBER,
FLIGHT_LIST_PASSENGER_ID,
FLIGHT_DATE_FLIGHT TIMESTAMP,
FLIGHT_CITY_FROM NVARCHAR2(100),
FLIGHT_CITY_TO NVARCHAR2(100),
CONSTRAINT FLIGHT_ID PRIMARY KEY(FLIGHT_ID),
CONSTRAINT FLIGHT_PLANE_ID_FK FOREIGN KEY(FLIGHT_PLANE_ID) REFERENCES PLANE(PLANE_ID)
);