CREATE TABLE PASSENGER(
PASSENGER_ID NUMBER,
PASSENGER_LAST_NAME NVARCHAR2(100),
PASSENGER_NATIONALITY NVARCHAR2(100),
PASSENGER_DATE_OF_BIRTH TIMESTAMP,
PASSENGER_PASSPORT_CODE NVARCHAR2(100),
PASSENGER_LIST_FLIGHT_ID NVARCHAR2(100),
CONSTRAINT PASSENGER_ID PRIMARY KEY(PASSENGER_ID)
);