CREATE TABLE Plane(
PLANE_ID NUMBER,
PLANE_MODEL NVARCHAR2(100),
PLANE_CODE NVARCHAR2(100),
PLANE_YEAR_PRODUCED TIMESTAMP,
PLANE_AVG_FUEL_CONSUMPTION NUMBER(*,2),
CONSTRAINT PLANE_ID PRIMARY KEY(PLANE_ID)
);